name: MLflow CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install MLflow
        run: |
          pip install mlflow==2.19.0

      - name: Run MLflow Project
        run: |
          mlflow run . --env-manager=local

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-artifacts
          path: MLProject/mlruns
