name: MLflow CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install mlflow==2.19.0 scikit-learn pandas matplotlib seaborn joblib

      - name: Run modelling.py
        run: |
          python MLProject/modelling.py

      - name: Upload model artifact
        uses: actions/upload-artifact@v4
        with:
          name: model-artifacts
          path: mlruns/**/artifacts/model/
